name: Run dbt Pipeline

on:
  workflow_dispatch:

jobs:
  run-dbt:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dbt
        run: pip install dbt-postgres
      
      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          dbt_test:
            target: dev
            outputs:
              dev:
                type: postgres
                host: ${{ secrets.DB_HOST }}
                user: ${{ secrets.DB_USER }}
                password: ${{ secrets.DB_PASSWORD }}
                port: 5432
                dbname: neondb
                schema: public
                threads: 1
                sslmode: require
          EOF
      
      - name: Debug connection
        run: dbt debug
      
      - name: Run dbt models
        run: dbt run
      
      - name: Run dbt tests
        run: dbt test